### ISSUE TITLE
Encoding problem with --text extract

### ISSUE THREAD

**Issue by Symryvvin** [HearthSim/UnityPack#12]
> D:\XML>python D:\unityUnpack\UnityPack-master\UnityPack-master\bin\unityextract
> --text "C:\Program Files\Hearthstone\Data\Win\cardxml0.unity3d"
> Traceback (most recent call last):
>   File "D:\unityUnpack\UnityPack-master\UnityPack-master\bin\unityextract", line
>  146, in <module>
>     main()
>   File "D:\unityUnpack\UnityPack-master\UnityPack-master\bin\unityextract", line
>  143, in main
>     exit(app.run())
>   File "D:\unityUnpack\UnityPack-master\UnityPack-master\bin\unityextract", line
>  56, in run
>     self.handle_asset(asset)
>   File "D:\unityUnpack\UnityPack-master\UnityPack-master\bin\unityextract", line
>  118, in handle_asset
>     self.write_to_file(filename, d.script, mode=mode)
>   File "D:\unityUnpack\UnityPack-master\UnityPack-master\bin\unityextract", line
>  76, in write_to_file
>     written = f.write(contents)
>   File "C:\Python35\lib\encodings\cp1251.py", line 19, in encode
>     return codecs.charmap_encode(input,self.errors,encoding_table)[0]
> UnicodeEncodeError: 'charmap' codec can't encode character '\xed' in position 15
> 59: character maps to <undefined>

**Comment by jleclanche** [comment]
I don't know why windows is using cp1251 encoding here. Default is supposed to be utf-8.

**Comment by ghost** [comment]
This is Russian version of Windows, Windows is a strange thing..
