### ISSUE TITLE
Image decoding error

### ISSUE THREAD

**Issue by andburn** [HearthSim/UnityPack#15]
Noticed this error extracting the texture for card CFM_648, format problem maybe?

`unityextract --images Hearthstone\Data\Win\cardtextures0.unity3d --filter HS9-007_M`

```
Traceback (most recent call last):
  File ".\bin\unityextract", line 146, in <module>
    main()
  File ".\bin\unityextract", line 143, in main
    exit(app.run())
  File ".\bin\unityextract", line 56, in run
    self.handle_asset(asset)
  File ".\bin\unityextract", line 127, in handle_asset
    image = d.image
  File "python-unitypack\unitypack\engine\texture.py", line 175, in image
    return Image.frombytes(mode, size, data, codec, args)
  File "Python3.5.2\lib\site-packages\PIL\Image.py", line 2070, in frombytes
    im.frombytes(data, decoder_name, args)
  File "Python3.5.2\lib\site-packages\PIL\Image.py", line 744, in frombytes
    raise ValueError("not enough image data")
ValueError: not enough image data
```

**Comment by robert-nix** [comment]
The format is very likely .crn data, not raw dxt: <https://github.com/BinomialLLC/crunch>

**Comment by andburn** [comment]
Yep, you're right. That's annoying.

**Comment by verng95** [comment]
I have the same error, as you ignore it and continue the algorithm?

**Comment by FardHast** [comment]
@andburn Almost the same error. Extracted 1923 arts out of 2818 needed. And then this error and program crashed. Please, I really hope you can do smth about it.
![exporting arts error](https://cloud.githubusercontent.com/assets/24718966/21429953/e2d61d82-c882-11e6-9fe5-f7e5ffd625e4.png)

**Comment by andburn** [comment]
@FardHast yeah, different project but same problem. I added an issue for it https://github.com/andburn/hs-art-extractor/issues/6 will try and fix it soon.

**Comment by FardHast** [comment]
@andburn Thanks!

**Comment by jleclanche** [comment]
This was fixed!
