### ISSUE TITLE
Add support for extracting, modifying, and packing.

### ISSUE THREAD

**Issue by ghost** [HearthSim/UnityPack#17]
Also support for .dll's
Then we could modify any unity3d game (create mods), or ~~hack~~ reverse-engineer for educational purpose.
You can add this functionality for games with Unity3D 5+, because Unity3D is the most popular version of Unity now.
All this features was in disunity (java), but it was supporting unity 3d up to latest 4 version, but not 5 (only alpha)

**Comment by jleclanche** [comment]
I'm not working on reserialization but you are more than welcome to. I'll take a PR for it (although please discuss it with me beforehand).
