### ISSUE TITLE
Format 17 with external files

### ISSUE THREAD

**Issue by maniacgit** [HearthSim/UnityPack#30]
I'm trying to extract images from the Zombicide Android app. This app has an obb file which can be extracted using zip.
After extracting I got a lot of files.
There are sharedassets1.assets.splitXX where XX is a number. I've joined them using cat since UnityPack seems it can't handle split files. I've already done this with an older version of the app using disunity and it worked fine.
Additional there are a lot of files which are named by 16 byte hex strings. If I search for those strings in sharedassets1.assets you can find them all in this file.
Before all those files start in the sharedassets1.assets I can read: resources/unity_builtin_extra
So I think they are related to the assets.

It's using Unity format 17.

If I try to extract I get this error:
  File "/usr/local/lib/python3.5/dist-packages/unitypack-0.6.1-py3.5.egg/unitypack/utils.py", line 104, in read_int
    return struct.unpack(self.endian + "i", self.read(4))[0]
struct.error: unpack requires a bytes object of length 4

**Comment by robert-nix** [comment]
Should be fixed by 11c22bc.
