### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by garysheffield19** [HearthSim/UnityPack#44]
Sorry for asking some stuipid questions.
I am not a programmer and this is my first time to use github.

I ued to extract unity3d files with Unity Studio but somehow it doesn't work with some files I got now.
So I googled new tool for extracting "UnityRaw" type data and I found Unitypack may be helpful.
But I don't know how to use it.
It looks like some kind of open codes. so where can I get the .exe?

If this kind of stupid issue may cause bad influence, just tell me and I will close/remove this issue.

**Comment by guycalledfrank** [comment]
Actually a good question. Some people only run python once in 5 years.

EDIT:

... last time I used python, it was version 2. Installing 3 and running
pip3 install unitypack

seemed to do the trick. Hopefully this will help someone.

**Comment by ScriptKittyJane** [comment]
Anyone got a good guide?
