### ISSUE TITLE
Publish a new PyPI release

### ISSUE THREAD

**Issue by EpocDotFr** [HearthSim/UnityPack#53]
It looks like it's been two months there were no new UnityPack release. However, I see in the commits list there were several bugfixes.

Is it possible to publish a new PyPi release with those fixes?

PS: awesome work, this project rocks!

**Comment by jleclanche** [comment]
I'm kinda uncertain whether the current state of master is healthy. @Mischanix have you tried it?

**Comment by robert-nix** [comment]
master's been fine for me.

**Comment by EpocDotFr** [comment]
It'll be awesome if you could make a new release soon 😁

**Comment by jleclanche** [comment]
According to haibane there are some issues in the latest master.

**Comment by EpocDotFr** [comment]
I tested latest `master` in my project.

Latest `master` not only works well, but also solves all my problems I had to parse an `.assets` file which comes from a recent version of Unity3d (I cannot tell you the exact version).

**Comment by EpocDotFr** [comment]
NVM. There's issues in the latest master, I bet when reading unknown objects data:

>   File "c:\users\maxime gross\appdata\local\programs\python\python35\lib\site-packages\unitypack\object.py", line 51, in type_tree
>    return TypeMetadata.default(self.asset).type_trees[self.class_id]
>KeyError: -134

**Comment by jleclanche** [comment]
0.8.0 is out
