### ISSUE TITLE
How to deal with MonoBehavior items?

### ISSUE THREAD

**Issue by EpocDotFr** [HearthSim/UnityPack#54]
I'm using UnityPack to extract specific items from an `.assets` file. I can extract the content of a TextAsset item without any issue, but what about other types like MonoBehavior? I see they aren't available at all in the `objects` attribute of an `Asset` instance, are they completely ignored during the parsing process?

Also, the UnityPack readme states:

> Not all base Unity3D classes are implemented. If a class is unimplemented, or a custom class (eg. a non-Unity class) is encountered, the resulting data is a dict of the fields instead. The same dict of fields can be found in the `_obj` attribute of the instance, otherwise.

Should this mean that the raw data of the MonoBehavior items should be available after all, even if UnityPack doesn't support this type of item?

Thank you in advance for your precision 😃

**Comment by ifeherva** [comment]
Exactly. MonoBehavior can be extracted if you define how.

**Comment by EpocDotFr** [comment]
What about the readme part I quoted?

**Comment by ifeherva** [comment]
That is how it works. You get a dict with the relevant fields and their data.

**Comment by EpocDotFr** [comment]
I'm sorry but I don't understand.

What I'm thinking I'm understanding about the readme quote is: if this item (e.g a MonoBehavior) cannot be cast as a Python class, just return the raw data as a dict. Am I wrong?

**Comment by ifeherva** [comment]
You are correct, you get a dict with the data as there is no MonoBehaviour class defined. You can of course define your class that takes the dict and interprets it.

**Comment by EpocDotFr** [comment]
Perfect! But, as stated in the description of this issue:

> what about other types like MonoBehavior? **I see they aren't available at all in the `objects` attribute of an `Asset` instance**

So how can I access MonoBehaviour dicts?

**Comment by EpocDotFr** [comment]
Nevermind. I'm dumb. I had a `break` in my loop, thus I wasn't looping on all items.
