### ISSUE TITLE
Support for TextureFormat.PVRTC_RGBA4

### ISSUE THREAD

**Issue by andyearnshaw** [HearthSim/UnityPack#57]
I get this for certain texture assets in some of the bundles I'm extracting:

```text
NotImplementedError: Unimplemented format <TextureFormat.PVRTC_RGBA4: 33>
```

It would be great if this format could be supported in the future.

**Comment by jleclanche** [comment]
It needs to be implemented in Pillow first: https://github.com/python-pillow/Pillow/ 

I'm closing this -- unity has a lot of texture formats but without a Pillow format for it there's not much I can do.

I recommend filing a PR with Pillow to implement it. [This might help](https://github.com/GreyRook/python-pvr).
