### ISSUE TITLE
Mistake? `read_cstring` error message uses `list` instead of `bytes`.

### ISSUE THREAD

**Issue by Raijinili** [HearthSim/UnityPack#60]
https://github.com/HearthSim/UnityPack/blob/e0e53d280537f495ef744657005a06dea3cd0694/unitypack/utils.py#L83

Shouldn't the error message use `b"".join` first? As is, the value is a bunch of single-byte strings.

Possible correction:

```python3
def read_cstring(self) -> bytes:
	retlst = []
	c = self.read(1)
	while c and c != b"\0":
		retlst.append(c)
		c = self.read(1)
	ret = "".join(retlst)
	if not c:
		raise ValueError("Unterminated string: %r" % (ret))
	return ret
```

**Comment by jleclanche** [comment]
Yeah that error message is fine. And your `ret = "".join(retlst)` would crash because you're trying to join bytes into a string (gotta decode first).
