### ISSUE TITLE
Malloc.h replaced by stdlib.h while installing

### ISSUE THREAD

**Issue by danielfrausto** [HearthSim/UnityPack#69]
Hi , while trying to install scrunch, I get the error "malloc.h replaced by stdlib.h" while installing. Using freebsd 11.1 and python3.

**Comment by jleclanche** [comment]
Issue moved to [HearthSim/decrunch #9](https://github.com/HearthSim/decrunch/issues/9) via [**ZenHub**](https://www.zenhub.com/)
