### ISSUE TITLE
ModuleNotFoundError: No module named 'unitypack'

### ISSUE THREAD

**Issue by Esr45** [HearthSim/UnityPack#71]
I have all of the requirements installed, but when I try to run any of the unityextract commands I get the following error. I am using windows 10. What am I doing wrong? I also ran setup.py and it worked fine

>python unityextract --help
Traceback (most recent call last):
  File "unityextract", line 5, in <module>
    import unitypack
ModuleNotFoundError: No module named 'unitypack'
```

**Comment by Aedial** [comment]
Since unityextract is not in your %PATH%, you need to type the absolute path to unityextract.
