### ISSUE TITLE
Trying to extract image file

### ISSUE THREAD

**Issue by captSpirk** [HearthSim/UnityPack#96]
I am trying to extract a UnityExtract image file, using 

`python unityextract --image_full_filename.SD`, but it's giving me this usage error:

`usage: unityextract [-h] [--all] [--audio]] [--fonts] [--images] [--models] [--shaders] [--text] [--video] [-o [OUTDIR]] [--as-asset] [filter [FILTER [FILTER ...]]] [-n] files [files ...]
unityextract: error: the following arguments are required: files`

What am I doing wrong?

**Comment by sebastientromp** [comment]
if `image_full_filename.SD` is your file name, you should call via either `python unityextract image_full_filename.SD` or `python unityextract -- image_full_filename.SD`

**Comment by captSpirk** [comment]
Where are the unityextract files save after successfully extracting the files?

**Comment by sebastientromp** [comment]
You can specify that with the `-o` option, eg `python unityextract -o out image_full_filename.SD` will save the extracted files to the `out/` folder.

**Comment by captSpirk** [comment]
Nothing is working. I'm using the -o option and specify the directory to save the file, but nothing shows up.

Does unityextract even work?

No errors so far, but there is nothing saved. Don't see any files. 

**EDIT: I got it working.**

**Comment by captSpirk** [comment]
I got it w
